### ISSUE TITLE
Should we dock the plugin at the bottom

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#105]
@palvarezc 
In the current view the user can't really see the table, and the buttons are quite large.
In testing, I acidentally docked the plugin to the bottom of the napari window and realised, we're probably better off having the layout something more like. It is possible to get this to be the default, and only requires changing a small bit of layout code to achieve.
![sketch](https://github.com/user-attachments/assets/fe952552-2ca0-4c36-bb51-d94c60827b41)

**Comment by samcunliffe** [comment]
[Zulip link](). Seems it's not possible to do it anywhere other than a launch script.

We could add an entrypoint script in `pyproject.toml` and ... we can make a python script be a shortcut in Windows (??).

Be good to confirm on the lab machines (Windows?)

**Comment by palvarezc** [comment]
@Joseph-Garvey added this to `launch_debuq.py`

**Comment by Joseph-Garvey** [comment]
> [Zulip link to discussion with napari devs](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Changing.20plugin.20default.20dock.20location/near/467318478). Seems it's not possible to do it anywhere other than a "launch" script.
> 
> We could add an entrypoint script in `pyproject.toml` and ... we can make a python script be a shortcut in Windows (??).
> 
> Be good to confirm on the lab machines (Windows?)

Yea I was thinking of a python launch script. Lab machines are windows, still trying to figure out how to get the conda install set up. Having issues with user accounts not being able to launch napari on the base environment if installed by admin.
