### ISSUE TITLE
Improve naming convention for the buttons

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#11]
We may need a better naming convention for the buttons.

_Originally posted by @samcunliffe in https://github.com/samcunliffe/cavendish-particle-tracks/pull/4#discussion_r1281168768_

**Comment by Joseph-Garvey** [comment]
In the past I've stuck to btn_event since the button parent is implied by what python script it's contained within. btn identifies it as a button where it isn't obvious from surrounding context. In this case it would follow btn_openstereowin, btn_savetable etc.
