### ISSUE TITLE
Test button show/hide functionality

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#110]
Low test coverage on PR #104 is preventing merge.
Need to test show/hide function to bring coverage back up.

**Comment by Joseph-Garvey** [comment]
@palvarezc

**Comment by samcunliffe** [comment]
Now covered by `test_widget.py::test_show_hide_buttons`

https://github.com/palvarezc/cavendish-particle-tracks/blob/bd237f21d20f9a3a0ea1d8a75837cd0264e56764/tests/test_widget.py#L277

Reached via 
- #116
