### ISSUE TITLE
Save dialog improvements

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#111]
- [ ] No user feedback when saving without anything loaded etc. Wait for button enable/disable to be merged and disable the save button when the user shouldn't be able to save.
 - [x] Doesn't automatically append .csv, user has to type .csv for file to save successfully. Good protection against bad filenames though.

_Originally posted by @Joseph-Garvey in https://github.com/palvarezc/cavendish-particle-tracks/issues/107#issuecomment-2338336885_

**Comment by samcunliffe** [comment]
Save button is currently enabled when no data is loaded. But there is meaningful feedback...
![Image](https://github.com/user-attachments/assets/8a2122c2-babf-4ba9-9c1d-a8f3809b0611)

When images is loaded, and there is no data in the table, the "Save" button is disabled.

**Comment by samcunliffe** [comment]
Okay, actually when we have `bypass_load_screen=True` then no buttons appear.

When data is loaded, the save button is disabled. So this is already reached via

- #131
