### ISSUE TITLE
Segfault when launching widget with viewer.window.add_plugin_dock_widget

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#113]
I encounter a problem that I do not really know how to test for:
              
              - Open the plugin with `python launch_debug.py`
              - Load data through the `Load data` dialog
              - Create a $\Lambda \to p \pi^-$ particle
              - Click `Calculate Decay angles`
              
              And I get a segfault :(
              
              Cannot reproduce when opening the plugin from within napari. But the problem is that with the new layout, the plugin is not usable if not displayed in the bottom.

_Originally posted by @palvarezc in https://github.com/palvarezc/cavendish-particle-tracks/issues/104#issuecomment-2343625664_

**Comment by Joseph-Garvey** [comment]
Problem unable to be reproduced on windows. Target environment is Windows, so will test on student pcs to be sure but may have to ignore this one for now.

**Comment by samcunliffe** [comment]
Can no longer reproduce. Seems solved via #114
