### ISSUE TITLE
Pop up windows appearing offscreen.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#119]
Seems to be an issue from before the horizontal dock feature was added.
Tried disabling, doesn't change behaviour.
It isn't currently an issue on main.

**Comment by samcunliffe** [comment]
Confirmed on current `HEAD` of `main` with bottom-docked (or top-docked!) widget startup. Does not happen when right-docked wither starting via command line, or via `launch_debug.py`.
