### ISSUE TITLE
Juanjo comments.

### ISSUE THREAD

**Issue by JaiJai14** [palvarezc/cavendish-particle-tracks#141]
Hi Paula (and others),

I have been playing around with the tool and it's very nice, congrats to everyone who worked on it. I think all of the methods for computing the different quantities are comprehensive and students should be able to get the hang of it quite quickly.  I will discuss briefly some comments that I had.

- When using the decay angles functionality, after quitting the submenu it will not let me load the functionality again to correct my calculation or to calculate it for a different particle. Pressing the button again will not load anything and I need to restart the plugging again to perform another angle measurement, losing all other measurements in the process.

- For some reason I can't select the front fiducials A' and E' for computing the magnification, but I can select all of the back fiducials. I don't know if this is intentional or not, sorry for my misunderstanding if it is.

- After computing the magnification and closing the submenu you don't get automatically taken back to the radii and lengths layer like you do after using the stereoshift submenu. This might look at first glance like the tools to add and remove points have disappeared. Of course you can just click on the radii and lengths layer to return to it, maybe just something to keep in mind if students ask.

- I might be completely wrong with this. However,  it seems to me like figure 3 in the lab script is x-mirrored with respect to the digital images. By this I mean that, from left to right, the front fiducials are D', B'F', C', A'E' in the images and A'E', C', B'F', D' in the figure. If this is the case, it would be nice to note this down somewhere. Maybe it could be a good idea to have a tickbox option to add small indicators of the x  and y axes in one of the image corners. This might help avoid confusion but I don't know how feasible it would be.

- Advise students to not click the "Change the order of visible axes" icon, it made my computer struggle a bit.

If, after using the tool a bit more, I happen to come up with any other comments I will let you know. Again great work, especially with how quickly it was completed. I am sure this tool will greatly improve the student experience for the practical.

Best wishes,
Juanjo

**Comment by Joseph-Garvey** [comment]
Thanks for testing and providing feedback!

> Advise students to not click the "Change the order of visible axes" icon, it made my computer struggle a bit.
This one's been on our minds but never committed to documentation. I'm surprised it didn't immediately crash as it does on my PC, as what clicking this button ends up doing is attempting to view the entire ~100GB dataset "end on" at once.

>When using the decay angles functionality, after quitting the submenu it will not let me load the functionality again to correct my calculation or to calculate it for a different particle. Pressing the button again will not load anything and I need to restart the plugging again to perform another angle measurement, losing all other measurements in the process.
>After computing the magnification and closing the submenu you don't get automatically taken back to the radii and lengths layer like you do after using the stereoshift submenu. This might look at first glance like the tools to add and remove points have disappeared. Of course you can just click on the radii and lengths layer to return to it, maybe just something to keep in mind if students ask.

Will raise issues for these. 1. I haven't encountered, 2. was implemented in the last update to magnification but the updates to stereoshift are yet to be merged. I'll get it added onto the same PR now.

>I might be completely wrong with this. However, it seems to me like figure 3 in the lab script is x-mirrored with respect to the digital images. By this I mean that, from left to right, the front fiducials are D', B'F', C', A'E' in the images and A'E', C', B'F', D' in the figure. If this is the case, it would be nice to note this down somewhere. Maybe it could be a good idea to have a tickbox option to add small indicators of the x and y axes in one of the image corners. This might help avoid confusion but I don't know how feasible it would be.

Easiest solution might be to just flip the dataset or flip the image in the handout. @palvarezc any thoughts?

>For some reason I can't select the front fiducials A' and E' for computing the magnification, but I can select all of the back fiducials. I don't know if this is intentional or not, sorry for my misunderstanding if it is.

@palvarezc needed for this one.

**Comment by palvarezc** [comment]
Thanks a million, Juanjo, very useful feedback!

> * When using the decay angles functionality, after quitting the submenu it will not let me load the functionality again to correct my calculation or to calculate it for a different particle. Pressing the button again will not load anything and I need to restart the plugging again to perform another angle measurement, losing all other measurements in the process.

Good catch! Fixed in #148 

> * For some reason I can't select the front fiducials A' and E' for computing the magnification, but I can select all of the back fiducials. I don't know if this is intentional or not, sorry for my misunderstanding if it is.

We do not have the coordinates of those fiducials in the bubble chamber, so we do not offer them for the calibration.

> * After computing the magnification and closing the submenu you don't get automatically taken back to the radii and lengths layer like you do after using the stereoshift submenu. This might look at first glance like the tools to add and remove points have disappeared. Of course you can just click on the radii and lengths layer to return to it, maybe just something to keep in mind if students ask.

Good point, the focus should go back to the main layer. Fixed in #147 

> * I might be completely wrong with this. However,  it seems to me like figure 3 in the lab script is x-mirrored with respect to the digital images. By this I mean that, from left to right, the front fiducials are D', B'F', C', A'E' in the images and A'E', C', B'F', D' in the figure. If this is the case, it would be nice to note this down somewhere. Maybe it could be a good idea to have a tickbox option to add small indicators of the x  and y axes in one of the image corners. This might help avoid confusion but I don't know how feasible it would be.

The images can indeed have possible rotations and reflections. Given the numbers are the right way up in the example images, I think it is probably a 180° rotation, but I worth adding a note to the script indeed.

**Comment by samcunliffe** [comment]
All fixes are now merged and will be in the next version.
