### ISSUE TITLE
Problems installing Napari on deployment machines

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#142]
Windows deployment machines use separate user accounts.
This creates issues with Conda installs.

User account must be an administrator to install.
When installing particle tracks + napari to the base, or a new virtual environment, the program functions as expected when launched from an administrator instance of powershell.
When installing to base, and running as a standard user, napari is present, but fails to launch.
When installing to napari-env and running as a standard user, napari is not present, despite being installed for the administrator.

**Comment by palvarezc** [comment]
When you are admin, do you need to use conda at all? Can you use `pip` from the system-wide python install to get napari?

**Comment by Joseph-Garvey** [comment]
Have tried using `pip` too. Same result.

**Comment by palvarezc** [comment]
Seems that the problem is the permission of the `napari` installation folder. For some reason (🐛), write access is needed for the user to be able to launch `napari`.

@Joseph-Garvey opened a [ticket](https://github.com/napari/napari/issues/7288).

**Comment by samcunliffe** [comment]
A thought which may or may not help:

`napari` do provide bundled installers. You might be able to [install `napari` for all users following these instructions](https://napari.org/stable/tutorials/fundamentals/installation_bundle_conda.html#how-to-install-the-windows-bundle).

That would leave a problem for installing the plugin.. either everyone installs the plugin with the `git+ssh` , `pip` package name, or (better, if it works) an admin does it and the plugin is available to everyone.


You will want to update the spec document to say we support Windows if this works.

**Comment by palvarezc** [comment]
Just checked the bundled installer, and found the same problem. The installation succeeds, but `napari` only launches successfully when it is run as administrator. Otherwise, it just stalls and produces the following traceback on `KeyboardInterrupt`:

```
Traceback (most recent call last):
  File "C:\ProgramData\napari-0.5.3\envs\napari-0.5.3\lib\tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\napari-0.5.3\\envs\\napari-0.5.3\\lib\\site-packages\\napari\\utils\\colormaps\\__pycache__\\tmp5yiyi6ng'
```

**Comment by palvarezc** [comment]
[This](https://github.com/python/cpython/issues/77680) might help?

**Comment by palvarezc** [comment]
It seems it is a [problem with `tempfile` in `python`](https://github.com/numba/numba/pull/9261). Will see if we can implement the workaround...

**Comment by palvarezc** [comment]
[This workaround](https://github.com/napari/napari/issues/7288#issuecomment-2376713049) works, so we can add it to the batch file that will eventually run the tool in the lab.
