### ISSUE TITLE
Make selection of fiducial wait for a click event

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#19]
Possible solution to
- #35 

I guess it's a ticket for UX improvements later. We can try searching the napari source.

              Yeah, I'd expect there to be a "points added" [event](https://napari.org/stable/guides/events_reference.html) that we can hook into. But I don't see anything obvious.

_Originally posted by @samcunliffe in https://github.com/samcunliffe/cavendish-particle-tracks/pull/18#discussion_r1284302102_

**Comment by samcunliffe** [comment]
Decided not to persue this.
