### ISSUE TITLE
Add UI tests for magnification application

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#34]
You could add a UI test which runs through the motions of calculating magnification and applying it to the table (click the radio button on/off). 

              Probably it's worth doing anyway but might be a bit too much snowballing for this PR.

_Originally posted by @samcunliffe in https://github.com/samcunliffe/cavendish-particle-tracks/pull/32#pullrequestreview-1565726255_

**Comment by samcunliffe** [comment]
[`_magnification_dialog.py` has the worst coverage](https://app.codecov.io/github/palvarezc/cavendish-particle-tracks/blob/main/src%2Fcavendish_particle_tracks%2F_magnification_dialog.py).

**Comment by Joseph-Garvey** [comment]
Fixed in #97
