### ISSUE TITLE
Retain magnification and stereoshift points layer once it has been created

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#47]
In the current version, a new points layer is created every time the magnification or stereoshift dialog is called. The magnification should be pretty consistent between images, and the reference points for the stereo shift are the same within one image (for different particles), therefore it would be better to retain the points layers in the background/hidden and make them active when those dialogs are called a second time. This way the user needs to reposition fewer points.

Tackle after 
- #48

**Comment by samcunliffe** [comment]
Done via
- #158
