### ISSUE TITLE
Automatically load images in groups of two or three

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#48]
Each event has three views, at least two of them are needed at once for the stereo shift method. Ideally we want a stack of "events", each of which has two or three image layers. Is this possible?

An idea would be to load the tree views as a stack, so that one can flick between them with the arrows in the keyboard. If we did this we would need to figure out a way to add some "Next event" and "Previous event" that allows the user to load the next or previous stack of three views.

**Comment by palvarezc** [comment]
Something interesting I learned when implementing the loading of the images as per #78:
-  Any layer of points/shapes defined **after** the image layers are added will have the same dimensions, meaning it will have the same 2D dimensions and the same 3rd dimension (i.e. event number/time). So effectively only one points layer is needed to keep track of measurements on different events. 
- Any layer created **before** seems to be by default only 2D, so when sliding through different events, e.g. the points in such a layer remain the same. This configuration would be suitable for the "Calibration layer".
- I suspect the behaviour before/after is just due to the change in default, so need to understand how to define the dimensions of the different layers at creation.

**Comment by Joseph-Garvey** [comment]
Interesting, I figured the "after" behaviour was the default, since it's designed for 3D images. I did take a look at a load of other napari plugins that used multiple image stacks to see how they were handling layers but they haven't quite handled it like I'd have liked to (+ time consuming reverse engineering their code). There's a few that were designed to take the stack layer and make it work better for 2D + t content.

**Comment by Joseph-Garvey** [comment]
Our issue has created some fuss over on the Napari repo. https://github.com/napari/napari/issues/7165
Seems they've been having issues with the IO code and the constraints of not wanting to break plugins etc. that it has become increasingly unmaintanable over time.
We might get a fix for Napari 0.5.2 but it's not looking promising.

**Comment by Joseph-Garvey** [comment]
Issue resolved in Napari. Just need to wait for 0.5.2 now.
https://github.com/napari/napari/issues/7165#event-13817536574
https://github.com/napari/napari/pull/7172
