### ISSUE TITLE
Dis/enable buttons at each step of the analysis or create relevant layers

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#49]
Either:
- At startup, only "New particle", "Magnification" and "Save" buttons should be enabled
- When 2 points have been added and selected, calculate length button should be enabled
- When 3 points have been added and selected, calculate radius button should be enabled

Or, similar to the behaviour of Calculate decay angles:
- When the calculate length button is clicked, create a new layer with 2 points and a widget to confirm & save to table
- When the calculate radius button is clicked, create a new layer with 3 points and a widget to confirm & save to table

Decide which is best and implement it 😁

**Comment by samcunliffe** [comment]
Solved via #131
