### ISSUE TITLE
Do we want dragable and resizable image layers?

### ISSUE THREAD

**Issue by palvarezc** [palvarezc/cavendish-particle-tracks#5]
We might want to be able to manipulate the two views independently until the fiducial markings overlay, for the measurement of the stereo shift.

Have a look at:
https://github.com/napari/napari/issues/299

Not 100% sure about this, need to test with real data.

**Comment by palvarezc** [comment]
For the moment implemented the solution of having an extra reference point, see #53.
This solution assumes there is no rotation of between the different views, but only translation. Need to check with real data whether this is true.

**Comment by samcunliffe** [comment]
Seems we've decided against this. So the answer to the issue title: **no**.
