### ISSUE TITLE
Layer handling should be improved

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#56]
All current code is written with references to layers by name.
This breaks when layers are renamed, resulting in layers not cleaning themselves up on window closes and calculations failing to update. Whilst the program functions as is, it may cause issues if users attempt to organise their annotations into different layers or mistakenly rename the default layers.

Proposed Solutions:
**Best**: Find another approach that doesn't rely upon this assumption. Perhaps using by prompting for a selection of the active layer (clumsy) or using the currently selected layer (possibly even more prone to user error).
**Better**: Restrict the user's ability to create or relabel layers. This restricts functionality, may not be possible in Napari (check this) but eliminates all known ways in which the user could cause the program to behave in an unexpected way.
**Sufficient:** We leave the program as is, but put clear instructions in the lab handout (preferably in bold) and in the program itself, perhaps utilising the bottom msg bar. This approach assumes the user is competent at reading instructions.

**Comment by samcunliffe** [comment]
Will be solved 
- https://github.com/palvarezc/cavendish-particle-tracks/pull/175

And was duplicated by
- #133
