### ISSUE TITLE
User is able to edit values in the tables.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#59]
User is able to edit values in the tables.
As far as I can tell (more testing required), changes made to the tables do not reflect in the internal data (ie. two way sync isn't on). Unsure whether this is desired functionality, but the lack of two-way sync means that any intentional edits are not reflected in the saved data. If edits are unintentional, then the user should not be able to edit the table.

**Comment by palvarezc** [comment]
Good catch, we dont need editable entries in the table.
The only exception would be to choose the decay channel of the Σ or Λ, if we go that way, see [need to create a new issue]
