### ISSUE TITLE
Update development requirements

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#68]
pytest plugin dependencies are causing local test runs to fail.
update development requirements to reflect those used for the github action.

**Comment by samcunliffe** [comment]
Can you share your error message?

Just to sanity check: you're doing 
```sh
python -m pip install -e ".[testing]"
```
... right?

That should pick up [`pyproject.toml`, we have a few pytest plugins](https://github.com/palvarezc/cavendish-particle-tracks/blob/main/pyproject.toml#L63) but it should just be those guys. Though, I suppose we make heavy use of Napari's own [`make_napari_viewer` plugin](https://github.com/napari/napari/blob/975759073cf81ca2de419e931416d07926aaa8c4/napari/utils/_testsupport.py#L179).

**Comment by Joseph-Garvey** [comment]
> python -m pip install -e ".[testing]"

Thanks, I learn something new everyday... Had written this issue as a note to self on learning to set up testing/development installations.
It was working fine after manually installing the dependencies in pyproject.toml, so I figured I could circle back to this issue near the end. This has at least saved me that time - thanks!
