### ISSUE TITLE
Function layouts

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#74]
Being slightly pedantic here, but noticed some of the function variables or constants being declared throughout the function. 
I've always been taught to lay out functions as:
1. constants + variable declarations at the start
2. the actual computing bits
such that any variables used can be found in one place, but I've seen arguments that they should be declared next to the lines where they're of relevance.

@samcunliffe is there any general rule on this for Python? Don't want to write code in a different layout as what's already here.

**Comment by samcunliffe** [comment]
Declare things close to where they're needed to minimise the context that the reader/reviewer has in their heads.

Your 1. and 2. are fine for small functions and files. But feels like it might be a FORTRAN convention..?


... I realise I'm answering a question more than one month after you asked it 🙃 . Missed the notification.
