### ISSUE TITLE
No user feedback given when saving to unpopulated table.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#86]
When clicking "save to table", the user is not given any feedback if they have not selected a particle in the table or the table is not populated.

**Comment by samcunliffe** [comment]
Presumably this refers to the "Save to table" button in the `DecayAnglesDialog`. Looks like this has been made obsolete by the workflow feature of showing/hiding buttons.

It's now not possible to open the `DecayAnglesDialog` without selecting a valid particle in the table.

![Image](https://github.com/user-attachments/assets/e6e8c012-e0ad-4eef-bf29-9e1148cdd7a9)


So closing as this was reached via
- #131
