### ISSUE TITLE
Unclear what view is being looked at.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#87]
Napari's import as stack imports the images in order (1,2,3) since they're named accordingly, but UX seriously harmed by not having the views labelled. Makes it quite confusing to use. Napari names the imported stack as the first file imported, disregarding the others.

**Comment by palvarezc** [comment]
In principle, if one uses the "Load data" feature implemented in #78 the view selected is used to name the stack. Would that fix the issue?
