### ISSUE TITLE
Divide by zero error thrown when points have the same shift.

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#89]
This will never happen if the user is selecting points correctly, but still possible.

**Comment by Joseph-Garvey** [comment]
Wait for UX Overhaul in PR #72

**Comment by samcunliffe** [comment]
On current `HEAD` of `main` I get a meaningful warning (not an exception) and we write `nan` to the data.


![Image](https://github.com/user-attachments/assets/248df8da-2f84-4be8-af05-1c56e0a283e8)


That's probably the behaviour we want: if we divide by zero then that's the only reasonable answer. Students can probably cope with excluding or recalculating `nan`s, I'd say.
