### ISSUE TITLE
UI Code Layout

### ISSUE THREAD

**Issue by Joseph-Garvey** [palvarezc/cavendish-particle-tracks#92]
Is there a generally accepted way to layout Qt UI code?
Currently the program vaguely follows:
1. Initialise all UI items + set parameters + function calls.
2. Setup UI layout for all items

This could be changed to more clearly group together the initialisations, parameters and call-backs rather than having them interwoven.

Alternatively, what I've seen in other examples of Qt code is:
1. Setup layout grid
2. Group together the instantiation, parameters, function calls and add to layout per item.
3. Repeat for every item in the UI

Essentially it's a question of whether to group by the type of action, or have all associated actions for a given piece of UI grouped together.

I can see the 2nd helping development in two ways:
-  When a single UI item needs to be edited as you don't end up missing a function call or parameter associated with that item.
- When adding text items that are static, we don't need multiple lines to both create the object and add it to the layout. This also saves a load of lbl_(itemname) names persisting when they never need to be referenced again outside of the UI setup script.

It's a small thing, but want to establish a standard now before I continue writing loads of UI code.

**Comment by samcunliffe** [comment]
I don't know about best practice, but I've previously done it by grouping into little private member functions (around either theme or type of UI element).

So some sketchy pseudocode would be:

```py
class MyWidget(QWidget):
    def __init__(
        self,
        napari_viewer: napari.Viewer,
        parent: QWidget | None = None,
    ):
        self._setup_main_layout()
        self._setup_top_row_buttons()
        self._setup_table()
        self._setup_bottom_row_buttons()

   def _setup_main_layout(self):
        self.setLayout(QVBoxLayout())

    def _setup_top_row_buttons(self):
        one = QPushButton(...)
        one.clicked.connect(self._on_click_button_one)
        two = QPushButton(...)
        two.clicked.connect(self._on_click_button_two)

        self.top_row_buttons = QVBoxLayout() # sublayouts if you like? or just directly to the main layout.
        self.top_row_buttons.add_widget(one)
        self.top_row_buttons.add_widget(two)

        self.layout().add_widget(self.top_row_buttons)

   # ...


        ...
```

Doesn't help with the big constructor, but maybe? hopefully? breaks things up.
